# Generated by Django 4.1.5 on 2023-01-29 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(blank=True, max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=11)),
                ('email', models.EmailField(max_length=50)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('senha', models.CharField(max_length=16)),
            ],
        ),
    ]
